---
title: "tables_primers"
author: "ragnva"
date: "27 4 2020"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) # for data wrangling and file download
library(knitr) # for the kable function
library(kableExtra) # for extended capabilities
library(readxl) #to read excel spredsheets
#install.packages("magick")
#install.packages("webshot")
#webshot::install_phantomjs()
library(magick)
library(webshot)


```

```{r data}
primers_all <- read_excel("./data/primers_overview.xlsx", na = "NA", sheet = 2) 


#First steps, decide what data to use and summarise
#Before we can start to format the table, we need to decide what data to #put in it. The goal here is to create a summary table of primer #characteristics. .
#Store in a new object, so that the raw data can be used later.



pri <- primers_all %>%
  rowwise() 


#Using dplyr::group:by() and dplyr::summarise() we can now create a summary table.

pri <- data.frame(pri) %>%
  ungroup() %>%
  group_by(Gene)


```

```{r primer_table_all, results ='asis'}
#The summary table is ready for making a table. In R Markdown chunk settings, we need to set the output format to results = "asis". This will print the table correctly. To create the table, all we need to do is to is to pipe it to kable().
 
 pri %>%
  kable(format = "html", col.names = c("Gene", 
                                       "Primers",
                                       "Sequence"), 
        caption = "All primers made for selected genes")%>%
  as_image()
  #add_header_above(c(" " = 1, "Female" = 2, "Male" = 2))   #1, 2 and 2 is the number of cols .



```






#####used_primers#####
