---
title: "tables_master_result"
author: "ragnva"
date: "26 5 2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(knitr)
library(dplyr)
library(biomaRt)
library(kableExtra)
library(lme4)
library(flextable)

#load data

time_rest <- readRDS("./derivedData/DE/mixedmodel2_timemodel.RDS")
full_rest <- readRDS("./derivedData/DE/mixedmodel2_fullmodel.RDS")

time_acute <- readRDS("./derivedData/DE/mixedmodel2_acutemodel_timeonly.RDS")
full_acute <- readRDS("./derivedData/DE/mixedmodel2_acutemodel.RDS")


# load list of all genes with ensemble info
all_genes <- readRDS("./derivedData/all_genes.RDS")

#load lncRNA

lncRNA <- readRDS("./derivedData/lncRNA.RDS")
 
    
```


```{r w2pre rest, results= "asis"}
 #####################make tables for results. 40 highest p.value##############
 

####rest w2pre #####


  
restw2 <- time_rest %>%
  filter(model %in% c("tissue_offset_lib_size_normalized"),
         coef %in% c("timew2pre")) %>%
  
  dplyr::select(gene, model, coef, estimate, se, z.val, p.val) %>%
  
  # filter out only lncRNA
  
  filter(gene %in% lncRNA$ensembl_gene_id) %>%
  # P-value adjustments
  group_by(model, coef) %>%
  mutate(p.adj = p.adjust(p.val, method = "fdr")) %>%
  print()

  
DE_rest_w2 <- restw2 %>%
  mutate(pt = if_else(p.adj < 0.01, "sig", "ns"),
         fc = if_else(estimate < -0.5 | estimate > 0.5 , "sig", "ns" )) %>% #significant if over 0,5 and -0,5
  mutate(inc_dec = if_else(estimate >0.00,"increase", "decrease")) %>%
  filter(pt == "sig" & 
         #inc_dec == "increase" &
         #fc == "sig" & 
         fc == "sig") %>%
  print()

# DE timew2pre 169
# DE increase 164
# DE decrease 5




                            ###arrange dataset on p.adjust

 w2_arranged <- arrange(DE_rest_w2,p.adj )
 
            ######sort out 40 best p adj values. Try to use top_n#############

 w2_p_table <- w2_arranged %>% 
 top_n(40, -p.adj) %>% 
  print()
 
 
                ##innerjoin with lncRNA to get hgnc symbol####
 w2_p_table <- w2_p_table %>% inner_join(lncRNA)
 
 
 ####write excel spreadsheet####
library(writexl)
#write_xlsx(w2_p_table, "./figures/w2_p_table.xlsx")

```



```{r w12 rest, results='asis'}
##############time w12#################


restw12 <- time_rest %>%
  filter(model %in% c("tissue_offset_lib_size_normalized"),
         coef %in% c("timew12")) %>%
  
  dplyr::select(gene, model, coef, estimate, se, z.val, p.val) %>%
  
  # filter out only lncRNA
  
  filter(gene %in% lncRNA$ensembl_gene_id) %>%
  # P-value adjustments
  group_by(model, coef) %>%
  mutate(p.adj = p.adjust(p.val, method = "fdr")) %>%
  print()




DE_rest_w12 <- restw12 %>%
  mutate(pt = if_else(p.adj < 0.01, "sig", "ns"),
         fc = if_else(estimate < -0.5 | estimate > 0.5 , "sig", "ns" )) %>% #significant if over 0,5 and -0,5
  mutate(inc_dec = if_else(estimate >0.00,"increase", "decrease")) %>%
  filter(pt == "sig" & 
           #inc_dec == "decrease" &
           #fc == "sig" & 
           fc == "sig") %>%
  print()


# DE lnc timew12 64
# 64 increase


                            

                          ###arrange dataset on p.adjust

 #w12_arranged <- arrange(DE_rest_w12,p.adj )
 
            
 
 
 ######sort out 40 best p adj values. Try to use top_n#############

 w12_p_table <- w12_arranged %>% 
 top_n(10, -p.adj) %>% #top10
  print()


                    ##innerjoin with lncRNA to get hgnc symbol####
 w12_p_table <- w12_p_table %>% inner_join(lncRNA)
 
 
  ####write excel spreadsheet####
library(writexl)
#write_xlsx(w12_p_table, "./figures/w12_p_table.xlsx")

```



                

```{r acute w2post, results='asis'}
#####acute model timepoint w2post #####

  acute_w2post <- time_acute %>%
  filter(model %in% c("lib_size_normalized"),
         coef %in% c("timew2post")) %>%
  dplyr::select(gene, model, coef, estimate, se, z.val, p.val) %>%
  
  # filter out only lncRNA
  
  filter(gene %in% lncRNA$ensembl_gene_id) %>%
  # P-value adjustments
  group_by(model, coef) %>%
  mutate(p.adj = p.adjust(p.val, method = "fdr")) %>%
  print()




DE_acute_w2post <- acute_w2post %>%
  mutate(pt = if_else(p.adj < 0.01, "sig", "ns"),
         fc = if_else(estimate < -0.5 | estimate > 0.5 , "sig", "ns" )) %>% #significant if over 0,5 and -0,5
  mutate(inc_dec = if_else(estimate >0.00,"increase", "decrease")) %>%
  filter(pt == "sig" & 
           #inc_dec == "decrease" &
           #fc == "sig" & 
           fc == "sig") %>%
  print()



#DE w2post 102
#increase 40
# decrease 62
 

                     ###arrange dataset on p.adjust

 w2post_arranged <- arrange(DE_acute_w2post,p.adj )
 
            ######sort out 40 best p adj values. Try to use top_n#############

 w2post_p_table <- w2post_arranged %>% 
 top_n(40, -p.adj) %>% 
  print()
 
 
                 ##innerjoin with lncRNA to get hgnc symbol####
 w2post_p_table <- w2post_p_table %>% inner_join(lncRNA)
 
  ####write excel spreadsheet####
library(writexl)
#write_xlsx(w2post_p_table, "./figures/w2post_p_table.xlsx")

```



```{r, venn diagram, results='asis'}

# Libraries
library(tidyverse)
library(hrbrthemes)
library(tm)
library(proustr)

# Load datasets
data1 <- DE_rest_w2 %>% 
  ungroup()
data2 <- DE_acute_w2post %>% 
  ungroup()
data3 <- DE_rest_w12 %>% 
  ungroup()

##trying to rbind datasets. It works. Now we have a dataset with all the sig lnc across different timepoints.

# Add datasets vertically, remember to ungroup.
 all_data <- rbind(data1, data2, data3) %>% 
   ungroup %>% 
   print()

all_data <- all_data %>% 
  group_by(coef) %>% 
  print()

####find duplicates. Does not work the way I wanted.
dups <- all_data %>% 
  group_by(gene, model, coef) %>% 
  mutate(Duplicated = case_when(length(gene)>1 ~ "Yes",
                            TRUE ~ "No")) %>%
  ungroup()



#select gene

dg1 <- data1 %>% 
  dplyr::select(gene)

dg2 <- data2 %>% 
  dplyr::select(gene)

dg3 <- data3 %>% 
  dplyr::select(gene)


#Trying to find similar genes at different timepoint.

#Shared genes

#intersect(intersect(a,b),c)
#More cleverly, and more conveniently if you have a lot of arguments:
#Reduce(intersect, list(a,b,c))

 time_goi <- Reduce(intersect, list(dg1, dg2, dg3))
 #17 lnc same across 3 timepoints'
 
 time_goi <- c("ENSG00000116652", "ENSG00000130600", "ENSG00000205056", "ENSG00000224361","ENSG00000224609", "ENSG00000225613",
	"ENSG00000229821",
	"ENSG00000230438",
	"ENSG00000237499",
	"ENSG00000260793",
	"ENSG00000260807",
	"ENSG00000260966",
	"ENSG00000263873",
	"ENSG00000265206",
	"ENSG00000266923",
	"ENSG00000273812"	,"ENSG00000286191")
 
 #save as RDS
 
 saveRDS(time_goi, "./derivedData/time_goi.RDS")

intersect(intersect (dg1, dg2), dg3)






#Genes in data1 but not in data2

setdiff(data1$gene, data2$gene)


#Genes in data2 but not in data1

setdiff(data2$gene, data1$gene)

 
 

 
 #make x
 
 
 x <- list(
   data1 %>% filter(coef =="timew2pre") %>% dplyr:: select(gene) %>% unlist(), 
    data2 %>% filter(coef =="timew2post")  %>% dplyr:: select(gene) %>% unlist(), 
    data3 %>% filter(coef =="timew12") %>% dplyr:: select(gene) %>% unlist())
 
#cMake the plot
 grid.newpage() # new blank paper to make the plot on.
temp <- venn.diagram(x,
  category.names = c("Timew2pre(169)" , "Timew2post (102)" , "Timew12 (64)"),
  filename = NULL,
  output = TRUE,
  imagetype="png" ,
          height = 480 , 
          width = 480 , 
          resolution = 1000,
          compression = "lzw",
          lwd = 1,
          col=c("#440154ff", '#21908dff', '#fde725ff'),
          fill = c(alpha("#440154ff",0.3), alpha('#21908dff',0.3), alpha('#fde725ff',0.3)),
          cex = 1,
          fontfamily = "sans",
          cat.cex = 1,
          cat.default.pos = "outer",
          cat.pos = c(-27, 27, 135),
          cat.dist = c(0.085, 0.085, 0.085),
          cat.fontfamily = "sans",
          cat.col = c("#440154ff", '#21908dff', '#fde725ff'),
          rotation = 1,
          euler.d = TRUE,
          reverse = FALSE,
          
        )
grid.draw(temp)


```




